### ISSUE TITLE
Error: EEXIST: file already exists -  if src and dest is the same

### ISSUE THREAD

**Issue by takaaptech** [tomaszczechowski/gulp-string-replace#17]
Hi!
If I put to src and desc the same file I get the error: Error: EEXIST: file already exists
How can I find and replace in the same file?
Thanks!

**Comment by tomaszczechowski** [comment]
What's the purpose of overriding the source file?
The idea of a plugin is to take a source and create a destination with replaced values, therefore, reading a stream and writing it to source as a single process is not supported.

**Comment by takaaptech** [comment]
Hi @tomaszczechowski 
I am using gulp and this plugin to find and replace some strings in the project config file.
Okie I see the purpose of this plugin and switch to replace-in-file plugin for my need
Thanks!
