### ISSUE TITLE
dist creates folder

### ISSUE THREAD

**Issue by fbacker** [tomaszczechowski/gulp-string-replace#4]
.pipe(gulp.dest('./build/config.js'))

this will create a **folder called config.js** and it that place the file config.js
how to specify the output file? Want to do something like this

     gulp.src(["./src/store/config.default.js"]) 
        .pipe(replace('#SERVER', 'test'))
        .pipe(gulp.dest('./src/store/config.js'))

**Comment by fbacker** [comment]
sorry, my bad. New to gulp.
Added gulp-concat and now it works

	 gulp.src("./src/store/config.default.js") 
		.pipe(replace('#SERVER', 'test'))
		.pipe(concat('config.js'))
		.pipe(gulp.dest('./src/store/'));

**Comment by tomaszczechowski** [comment]
Great that you found solution. 
If you don't mind please rate project 😄
