### ISSUE TITLE
Recommend to by default not show all the files that didnt get replaced [logs.notReplaced default=false]

### ISSUE THREAD

**Issue by ericnewton76** [tomaszczechowski/gulp-string-replace#5]
logs.notReplaced default should be false, not true.

This seems more like noise to me, usually I'm replacing a cachebuster value that only applies to two files, but i needs to look through all the html files for any cachebuster references.

**Comment by tomaszczechowski** [comment]
Agree, please use version 0.3.0 with this enhancement. 

Don't forget to rate project 😄
