### ISSUE TITLE
What is 'allown' in README?

### ISSUE THREAD

**Issue by Splaktar** [tomaszczechowski/gulp-string-replace#6]
The following comment is repeated a number of times.

```
// Every file allown.
```

It's not clear to me what this is trying to say? 
Should this be `// Every file is allowed`? 
Should it just say that any file globs are supported?

**Comment by tomaszczechowski** [comment]
Hi Splaktar, 

Yes, there should be **_// Any file globs is supported_** or **_// Any type of file is allowed._** 
Sorry for this typo, I wanted to publish it asap 😄 

 It will be fixed today.

**Comment by Splaktar** [comment]
OK, great! Thank you very much for the prompt reply. Hopefully this will remove some of the confusion for new users who are looking at using this library. Thank you for your work!
