### ISSUE TITLE
Not replaces keeps showing up regardless of options?

### ISSUE THREAD

**Issue by anguila** [tomaszczechowski/gulp-string-replace#7]
I'm using: 
`var options = {
		logs		: { enabled: true},
		notReplaced : { enabled: false}
	};   
`

And if a regex is not matched it keeps showing up...

Cheers,

David

**Comment by anguila** [comment]
oops.. wrong format:
	var options = {
		logs: { 
			enabled: true,
			notReplaced : false
			},
	};

**Comment by tomaszczechowski** [comment]
😄
