### ISSUE TITLE
Pipeline character crashes 

### ISSUE THREAD

**Issue by Toldry** [tomaszczechowski/gulp-string-replace#9]
For example, say we got the file `foo.js` which contains the text

`var hello = world || "universe"`

in the gulpfile:

```javascript
gulp.task('replace-pipeline', function() {
    var substring = 'world ||';

    return gulp.src('foo.js')
        .pipe(replace(substring, ''))
        .pipe(gulp.dest('dist'));
});
```

The result is that the `substring` is interpreted as a regex and matches every empty string, and so the replacement does nothing

What I'd expect in this case is that the output of the replacement would be:

`var hello = "universe"`

**Comment by tomaszczechowski** [comment]
Essentially it is not an issue since you can interpret a seeking match using different regex expression:

```javascript
gulp.task('replace-pipeline', function() {
    return gulp.src('foo.js')
        .pipe(replace(/world \|\|/g, ''))
        .pipe(gulp.dest('dist'));
});
```

Don't forget to rate project 😄

**Comment by Toldry** [comment]
Shouldn't you specify in the README that entering a string will be
interpreted as a regex, then?

I thought string replacement was string replacement, and regex was a
separate overload

I'll be glad to rate! Where do you rate in github though? 😯

**Comment by tomaszczechowski** [comment]
indeed it may be misleading. I will do something with it in near future but for a time being use my workaround, please. 

You can rate project using a "star" button 😄
